// w8-core/src/vm/jit/memory.rs
//
//! # JIT compiler memory
//!
//! [`JITMemory`] represents a region of memory used to store machine code
//! generated by the JIT compiler.
//!
//! The memory is managed separately from ordinary Rust heap allocations
//! because JIT code must eventually reside in executable memory.
use std::{
    fmt::{self, Display, Formatter},
    ptr::{NonNull, copy_nonoverlapping},
};

#[cfg(windows)]
use std::ptr::null;
#[cfg(windows)]
use windows_sys::Win32::System::Memory::{
    MEM_COMMIT, MEM_RESERVE, PAGE_EXECUTE, PAGE_EXECUTE_READ, PAGE_EXECUTE_READWRITE,
    PAGE_PROTECTION_FLAGS, PAGE_READONLY, PAGE_READWRITE, VirtualAlloc, VirtualFree,
    VirtualProtect,
};

#[cfg(unix)]
use libc::{
    MAP_ANONYMOUS, MAP_FAILED, MAP_PRIVATE, PROT_READ, PROT_WRITE, c_int, mmap,
    mprotect, munmap,
};
#[cfg(unix)]
use std::ptr::null_mut;

use crate::vm::err::{VMError, VMErrorKind};

/// Memory protection permissions.
///
/// Memory protection determines which operations are allowed on a region of
/// virtual memory:
///
/// - **R (Read)** — memory can be read;
/// - **W (Write)** — memory can be modified;
/// - **X (Execute)** — memory can be executed as machine code.
///
/// Permissions can be combined.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct MemoryProtection(u8);

impl MemoryProtection {
    pub const READ: Self = Self(1);
    pub const WRITE: Self = Self(2);
    pub const EXECUTE: Self = Self(4);

    /// Checks whether this protection contains all permissions specified by
    /// `other`.
    pub const fn contains(self, other: Self) -> bool {
        self.0 & other.0 == other.0
    }
}

impl Display for MemoryProtection {
    fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
        if self.contains(Self::READ) {
            f.write_str("R")?;
        }

        if self.contains(Self::WRITE) {
            f.write_str("W")?;
        }

        if self.contains(Self::EXECUTE) {
            f.write_str("X")?;
        }

        Ok(())
    }
}

impl std::ops::BitOr for MemoryProtection {
    type Output = Self;

    fn bitor(self, rhs: Self) -> Self::Output {
        Self(self.0 | rhs.0)
    }
}

#[cfg(windows)]
impl From<MemoryProtection> for PAGE_PROTECTION_FLAGS {
    fn from(val: MemoryProtection) -> PAGE_PROTECTION_FLAGS {
        match val.0 {
            1 => PAGE_READONLY,
            2 => PAGE_READWRITE,
            3 => PAGE_READWRITE,
            4 => PAGE_EXECUTE,
            5 => PAGE_EXECUTE_READ,
            6 => PAGE_EXECUTE_READWRITE,
            7 => PAGE_EXECUTE_READWRITE,
            _ => unreachable!("invalid `MemoryProtection` value"),
        }
    }
}

#[cfg(unix)]
impl From<MemoryProtection> for c_int {
    fn from(protection: MemoryProtection) -> Self {
        let mut result = 0;

        if protection.contains(MemoryProtection::READ) {
            result |= libc::PROT_READ;
        }

        if protection.contains(MemoryProtection::WRITE) {
            result |= libc::PROT_WRITE;
        }

        if protection.contains(MemoryProtection::EXECUTE) {
            result |= libc::PROT_EXEC;
        }

        result
    }
}

/// A region of memory containing JIT-generated machine code.
pub struct JITMemory {
    /// Pointer to the beginning of the allocated memory region.
    pointer: NonNull<u8>,
    size: usize,

    /// Current memory protection of the allocated region.
    ///
    /// This value represents the protection that `JITMemory` expects the
    /// operating system to have assigned to the region.
    current_protection: MemoryProtection,
}

impl JITMemory {
    /// Initialize [`JITMemory`].
    pub fn malloc(size: usize) -> Result<Self, VMError> {
        let pointer: NonNull<u8>;
        #[cfg(windows)]
        {
            let ptr = unsafe {
                VirtualAlloc(
                    // `lpAddress` is the desired address at which Windows should allocate the memory.
                    // `std::ptr::null()` here means that the address is chosen by Windows.
                    null(),
                    // `dwSize` is the size of the memory region to allocate, in bytes.
                    size,
                    // `flAllocationType` is a set of flags that tells Windows what to do with
                    // the virtual memory.
                    //
                    // `MEM_RESERVE` reserves a range of virtual addresses for the process.
                    // `MEM_COMMIT` makes the reserved pages available for use.
                    //
                    // Using both flags at once reserves and commits the memory in a single call.
                    MEM_RESERVE | MEM_COMMIT,
                    // `flProtect` specifies the memory protection of the allocated pages.
                    //
                    // `PAGE_READWRITE` allows the memory to be both read from and written to.
                    // The memory is not executable at this point.
                    PAGE_READWRITE,
                )
            };

            if ptr.is_null() {
                return Err(VMError::new(VMErrorKind::JITAllocationFailed));
            }

            let ptr = ptr.cast::<u8>();

            pointer = NonNull::new(ptr).unwrap();
        }
        #[cfg(unix)]
        {
            let ptr = unsafe {
                mmap(
                    // `addr` is the desired address at which the memory region should be mapped.
                    // `std::ptr::null_mut()` means that the address is chosen by the OS.
                    null_mut(),
                    // `length` is the size of the memory region to map, in bytes.
                    size,
                    // `prot` specifies the protection of the mapped memory.
                    //
                    // `PROT_READ` allows the memory to be read from.
                    // `PROT_WRITE` allows the memory to be written to.
                    PROT_READ | PROT_WRITE,
                    // `flags` specifies how the mapping should be created.
                    //
                    // `MAP_PRIVATE` makes modifications to the mapping private to this
                    // process; they are not visible through the underlying object.
                    // `MAP_ANONYMOUS` creates a mapping that is not backed by a file.
                    //
                    // Together, these flags create private anonymous memory.
                    MAP_PRIVATE | MAP_ANONYMOUS,
                    // `fd` is the file descriptor of the object backing the mapping.
                    // `-1` is used with `MAP_ANONYMOUS` because the mapping has no file
                    // backing.
                    -1,
                    // `offset` is the offset into the backing object at which the mapping
                    // begins. For an anonymous mapping, it must be zero.
                    0,
                )
            };

            if ptr == MAP_FAILED {
                return Err(VMError::new(VMErrorKind::JITAllocationFailed));
            }

            pointer = NonNull::new(ptr.cast::<u8>())
                .ok_or(VMError::new(VMErrorKind::JITAllocationFailed))?;
        }

        Ok(Self {
            pointer,
            size,
            current_protection: MemoryProtection::READ | MemoryProtection::WRITE,
        })
    }

    /// Returns the base address of the JIT memory region.
    ///
    /// The code generator embeds absolute addresses derived from this base
    /// (the address table for dynamic jumps). The mapping is fixed for the
    /// lifetime of the region, so addresses captured at codegen time stay
    /// valid while the code executes.
    pub(crate) fn base_address(&self) -> u64 {
        self.pointer.as_ptr() as u64
    }

    /// Writes machine code into the JIT memory region.
    ///
    /// ## Arguments
    /// - `offset` is the byte offset from the beginning of the allocated
    ///   memory area where the machine code is to be written;
    /// - `code` is the code to be written.
    ///
    /// The entire `code` slice must fit within the allocated region. If the
    /// resulting range would exceed the region's bounds, or if calculating the
    /// end offset overflows `usize`, [`VMErrorKind::JITMemoryOutOfBounds`] is
    /// returned and no memory is written.
    pub fn write(&mut self, offset: usize, code: &[u8]) -> Result<(), VMError> {
        // Check that we can change data in memory.
        if !self.current_protection.contains(MemoryProtection::WRITE) {
            return Err(VMError::new(VMErrorKind::CantWriteCodeInTheCurrentPage(
                self.current_protection,
            )));
        }

        // Calculate the exclusive end of the range that will be written.
        //
        // `checked_add` is used instead of ordinary addition so that an integer
        // overflow cannot produce an invalid end offset.
        let end = offset
            .checked_add(code.len())
            .ok_or(VMError::new(VMErrorKind::JITMemoryOutOfBounds))?;

        // Ensure that the complete machine-code slice fits inside the allocated
        // memory region.
        if end > self.size {
            return Err(VMError::new(VMErrorKind::JITMemoryOutOfBounds));
        }

        unsafe {
            // `code.as_ptr()` points to the first byte of the machine-code slice.
            //
            // `self.pointer.as_ptr().add(offset)` calculates the destination
            // address by advancing `offset` bytes from the beginning of the JIT
            // memory region. Since the pointer points to `u8`, advancing it by
            // one element advances it by exactly one byte.
            //
            // `copy_nonoverlapping` then copies `code.len()` bytes from the source
            // slice into the destination region.
            //
            // The bounds check above guarantees that the entire destination range
            // lies within the allocated JIT memory. The source and destination are
            // also expected to be non-overlapping, as required by
            // `copy_nonoverlapping`.
            copy_nonoverlapping(code.as_ptr(), self.pointer.as_ptr().add(offset), code.len());
        }

        Ok(())
    }

    /// Changes the memory protection of the JIT compiler's memory region.
    ///
    /// Memory protection defines which operations the process is allowed to
    /// perform on a region of virtual memory.
    ///
    /// On Windows, this is implemented using `VirtualProtect`. On Unix
    /// platforms, it is implemented using `mprotect`.
    ///
    /// ## Arguments
    ///
    /// - `protection` — the new memory protection to apply to the JIT memory
    ///   region.
    ///
    /// ## Errors
    ///
    /// Returns [`VMErrorKind::JITMemoryProtectionFailed`] if the operating
    /// system fails to change the memory protection.
    pub fn protect(&mut self, protection: MemoryProtection) -> Result<(), VMError> {
        #[cfg(windows)]
        {
            // Windows does not provide protection flags that represent write-only or
            // write-and-execute memory without read permission. Reject these combinations
            // so that `current_protection` always matches the protection actually applied
            // by the operating system.
            if protection.contains(MemoryProtection::WRITE)
                && !protection.contains(MemoryProtection::READ)
            {
                return Err(VMError::new(VMErrorKind::JITMemoryProtectionFailed));
            }

            let mut old_protection = PAGE_READWRITE;

            // `VirtualProtect` changes the protection of a region of virtual
            // memory. It returns a non-zero value on success and zero on failure.
            let result = unsafe {
                VirtualProtect(
                    // `lpAddress` is a pointer to the beginning of the memory
                    // region whose protection should be changed.
                    self.pointer.as_ptr().cast(),
                    // `dwSize` is the size of the memory region in bytes.
                    self.size,
                    // `flNewProtect` specifies the new protection to apply.
                    protection.into(),
                    // `lpflOldProtect` receives the previous memory protection.
                    &mut old_protection,
                )
            };

            if result == 0 {
                return Err(VMError::new(VMErrorKind::JITMemoryProtectionFailed));
            }
        }

        #[cfg(unix)]
        {
            // `mprotect` changes the memory protection of a range of virtual
            // memory. It returns `0` on success and `-1` on failure.
            let result = unsafe {
                mprotect(
                    // `addr` is a pointer to the beginning of the memory region
                    // whose protection should be changed.
                    self.pointer.as_ptr().cast(),
                    // `len` is the size of the memory region in bytes.
                    self.size,
                    // `prot` specifies the new memory protection.
                    protection.into(),
                )
            };

            if result != 0 {
                return Err(VMError::new(VMErrorKind::JITMemoryProtectionFailed));
            }
        }

        self.current_protection = protection;

        Ok(())
    }

    /// Executes the machine code stored at the beginning of the JIT memory region.
    ///
    /// The memory region must have execute permission. The generated code must
    /// also be valid machine code with the following function signature:
    ///
    /// ```text
    /// extern "C" fn()
    /// ```
    ///
    /// ## Safety
    ///
    /// This function is unsafe because the caller must ensure that the memory
    /// contains valid executable code with the expected calling convention and
    /// function signature.
    pub fn execute(&self) -> Result<(), VMError> {
        if !self.current_protection.contains(MemoryProtection::EXECUTE) {
            todo!("Сделай для этой паники отдельную ошибку, лентяй.") // TODO: make special VM error for this.
        }

        // The beginning of the allocated region is treated as the entry point of
        // the generated machine code.
        let entry: extern "C" fn() = unsafe { std::mem::transmute(self.pointer.as_ptr()) };

        entry();

        Ok(())
    }
}

impl Drop for JITMemory {
    fn drop(&mut self) {
        #[cfg(windows)]
        unsafe {
            use windows_sys::Win32::System::Memory::MEM_RELEASE;

            VirtualFree(self.pointer.as_ptr().cast(), 0, MEM_RELEASE);
        }

        #[cfg(unix)]
        unsafe {
            munmap(self.pointer.as_ptr().cast(), self.size);
        }
    }
}
